import NavBar from "@/components/NavBar.jsx";
import { Inter } from "next/font/google";
import { Toaster } from "react-hot-toast";
import { TaskProvider } from "../context/TasksContext";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>{"Richard's To do"}</title>
      </head>
      <body className={inter.className}>
        <NavBar />
        <TaskProvider>
          {children}
          <Toaster />
        </TaskProvider>
      </body>
    </html>
  );
}
